global:
  resolve_timeout: 2m

route:
  receiver: "slack-alerts"
  group_by: ["alertname", "instance"]
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 12h

receivers:
  - name: "slack-alerts"
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL}
        channel: ${SLACK_CHANNEL}
        send_resolved: true
        title: >-
          {{ if eq .Status "firing" }}
            🚨 Alert: Machine Health Alerts - {{ .CommonLabels.instance }}
          {{ else }}
            ✅ Resolved: Machine Health Alerts - {{ .CommonLabels.instance }}
          {{ end }}
        text: >-
          {{ if eq .Status "firing" }}
            Alert Details:
            - Instance: {{ .CommonLabels.instance }}
            - Job: {{ .CommonLabels.job }}
            - Severity: {{ .CommonLabels.severity }}
            - Description: {{ .CommonAnnotations.description }}
          {{ else }}
            Resolved Details:
            - Instance: {{ .CommonLabels.instance }}
            - Job: {{ .CommonLabels.job }}
            - Severity: {{ .CommonLabels.severity }}
            - The `Machine down` issue has been resolved at {{ .CommonLabels.instance }}.
          {{ end }}
