global:
  resolve_timeout: 5m

route:
  receiver: "slack-alerts"
  group_by: ["alertname", "instance"]
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 12h

receivers:
  - name: "slack-alerts"
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL}
        channel: ${SLACK_CHANNEL}
        send_resolved: true
        title: "{{ .CommonAnnotations.summary }}"
        text: "{{ .CommonAnnotations.description }}"
