services:
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    volumes:
      - ./:/etc/alertmanager:ro
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
