services:
  prometheus:
    extends:
      file: ./prometheus/compose.yaml
      service: prometheus
    ports:
      - 9090:9090
    networks: 
      - prometheus-grafana

  alertmanager:
    extends:
      file: ./alertmanager/compose.yaml
      service: alertmanager
    ports:
      - 9093:9093
    networks:
      - prometheus-grafana
  
  grafana:
    extends:
      file: ./grafana/compose.yaml
      service: grafana
    networks:
      - prometheus-grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://prometheus:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  prometheus-grafana:
    name: prometheus-grafana
volumes:
  prometheus-data:
    name: prometheus-data
