groups:
  - name: TargetHealthAlerts
    rules:
      - alert: TargetDown
        expr: up ==0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Machine Down Alert: {{ $labels.job }} at {{ $labels.instance }}"
          description: "The target {{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
