global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: node-exporter
    scrape_interval: 3s
    static_configs:
      - targets: # need to isolate `targets` value so that it can be inserted from another file or variable.
          - yureutae-server-1:9988
          - yureutae-server-2:9988
          - yureutae-server-3:9988
