services:
  prometheus:
    extends:
      file: ${PGM_HOME}/prometheus/docker-compose.yaml
      service: prometheus
    networks: 
      - prometheus-grafana
  
  grafana:
    extends:
      file: ${PGM_HOME}/grafana/docker-compose.yaml
      service: grafana
    networks:
      - prometheus-grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://prometheus:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  prometheus-grafana:
    name: prometheus-grafana
volumes:
  prometheus-data:
    name: prometheus-data
